#!/usr/bin/env python3
"""
JS Forge - DEBUG TOOLKIT
Use this to trace every step of JavaScript execution
"""

import sys
import os
import io
from contextlib import redirect_stdout

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from lexer import Lexer, TokenType
from parser import Parser, ASTNode
from interpreter import Interpreter, JSError

def print_header(title):
    print("\n" + "=" * 70)
    print(f"  {title}")
    print("=" * 70)

def debug_tokens(source):
    """Show every token generated by the lexer"""
    print_header("STEP 1: LEXER (Tokenization)")
    try:
        lexer = Lexer(source)
        tokens = lexer.tokenize()
        print(f"Total tokens: {len(tokens)}")
        print(f"{'#':<4} {'Type':<20} {'Value':<25} {'Raw':<20} {'Pos'}")
        print("-" * 70)
        for i, t in enumerate(tokens):
            val = repr(t.value) if t.value is not None else "None"
            if len(val) > 22:
                val = val[:19] + "..."
            raw = repr(t.raw) if t.raw else "''"
            if len(raw) > 18:
                raw = raw[:15] + "..."
            print(f"{i:<4} {t.type.name:<20} {val:<25} {raw:<20} L{t.line}:C{t.column}")
        return tokens
    except Exception as e:
        print(f"❌ LEXER ERROR: {e}")
        raise

def debug_ast(tokens):
    """Show the Abstract Syntax Tree"""
    print_header("STEP 2: PARSER (AST)")
    try:
        parser = Parser(tokens)
        ast = parser.parse()
        print_ast_node(ast, 0)
        return ast
    except Exception as e:
        print(f"❌ PARSER ERROR: {e}")
        raise

def print_ast_node(node, indent):
    """Pretty print AST nodes"""
    prefix = "  " * indent
    if node is None:
        print(f"{prefix}None")
        return

    node_type = type(node).__name__

    # Print node type and key attributes
    attrs = []
    if hasattr(node, 'name') and node.name:
        attrs.append(f"name='{node.name}'")
    if hasattr(node, 'value') and node.value is not None:
        attrs.append(f"value={repr(node.value)}")
    if hasattr(node, 'operator') and node.operator:
        attrs.append(f"operator='{node.operator}'")
    if hasattr(node, 'kind') and node.kind:
        attrs.append(f"kind='{node.kind}'")
    if hasattr(node, 'line') and node.line:
        attrs.append(f"line={node.line}")

    attr_str = ", ".join(attrs)
    if attr_str:
        print(f"{prefix}{node_type} ({attr_str})")
    else:
        print(f"{prefix}{node_type}")

    # Recursively print children
    for field_name in ['body', 'expression', 'declarations', 'init', 'test', 
                       'consequent', 'alternate', 'left', 'right', 'argument',
                       'callee', 'object', 'property', 'elements', 'properties',
                       'params', 'id', 'update']:
        if hasattr(node, field_name):
            child = getattr(node, field_name)
            if child is not None:
                if isinstance(child, list):
                    if child:
                        print(f"{prefix}  .{field_name}:")
                        for item in child:
                            print_ast_node(item, indent + 2)
                elif isinstance(child, ASTNode):
                    print(f"{prefix}  .{field_name}:")
                    print_ast_node(child, indent + 2)

def debug_execution(ast, verbose=False):
    """Execute and show output"""
    print_header("STEP 3: INTERPRETER (Execution)")
    try:
        interpreter = Interpreter()

        f = io.StringIO()
        with redirect_stdout(f):
            interpreter.run(ast)

        output = f.getvalue()
        if output.strip():
            print("Output:")
            for i, line in enumerate(output.strip().split("\n"), 1):
                print(f"  [{i}] {line}")
        else:
            print("(no output)")

        return output
    except Exception as e:
        print(f"❌ RUNTIME ERROR: {e}")
        raise

def debug_full(source, label="Code"):
    """Run full debug pipeline"""
    print("\n" + "🔍 " * 25)
    print(f"DEBUGGING: {label}")
    print("🔍 " * 25)

    print(f"\nSource code:")
    for i, line in enumerate(source.split("\n"), 1):
        print(f"  {i:3d}| {line}")

    tokens = debug_tokens(source)
    ast = debug_ast(tokens)
    output = debug_execution(ast)

    print_header("RESULT")
    print(f"✅ Execution completed successfully")
    print(f"Output lines: {len(output.strip().split(chr(10))) if output.strip() else 0}")
    return output

def debug_file(filepath):
    """Debug a JS file"""
    with open(filepath, 'r') as f:
        source = f.read()
    return debug_full(source, f"File: {filepath}")

def debug_test(test_name, source, expected):
    """Debug a single test case with expected output"""
    print("\n" + "🧪 " * 25)
    print(f"TEST: {test_name}")
    print("🧪 " * 25)

    try:
        tokens = debug_tokens(source)
        ast = debug_ast(tokens)
        output = debug_execution(ast)

        actual = output.strip().split("\n") if output.strip() else []

        print_header("VERIFICATION")
        print(f"Expected: {expected}")
        print(f"Actual:   {actual}")

        if actual == expected:
            print("✅ TEST PASSED")
            return True
        else:
            print("❌ TEST FAILED")
            print(f"\nMismatch at:")
            for i, (exp, act) in enumerate(zip(expected, actual)):
                if exp != act:
                    print(f"  Line {i+1}: expected '{exp}', got '{act}'")
            if len(expected) != len(actual):
                print(f"  Length mismatch: expected {len(expected)}, got {len(actual)}")
            return False

    except Exception as e:
        print(f"❌ TEST CRASHED: {e}")
        import traceback
        traceback.print_exc()
        return False

def main():
    import argparse
    parser = argparse.ArgumentParser(description="JS Forge Debug Toolkit")
    parser.add_argument("file", nargs="?", help="JavaScript file to debug")
    parser.add_argument("-c", "--code", help="Debug code string directly")
    parser.add_argument("-t", "--test", help="Run specific test file")
    args = parser.parse_args()

    if args.code:
        debug_full(args.code, "Inline Code")
    elif args.file:
        debug_file(args.file)
    elif args.test:
        # Run a test from the test suite
        test_files = {
            "1": ("TC-1: Odd/Even", "tests/test1.js", ["7 is Odd"]),
            "2": ("TC-2: Triangle", "tests/test2.js", ["*", "**", "***", "****", "*****"]),
            "3": ("TC-3: Armstrong", "tests/test3.js", ["true", "false"]),
            "4": ("TC-4: Array Reverse", "tests/test4.js", ["Original: 1, 2, 3, 4, 5", "Reversed: 5, 4, 3, 2, 1"]),
            "5": ("TC-5: Palindrome", "tests/test5.js", ["racecar is a Palindrome"]),
            "6": ("HT-1: Arrow Functions", "tests/test6_arrow_functions.js", ["7", "25", "Hello"]),
            "7": ("HT-3: Type Coercion", "tests/test8_type_coercion.js", ["true", "false", "true", "false", "true", "false", "true", "false"]),
            "8": ("HT-4: Array Methods", "tests/test9_array_methods.js", ["2, 4, 6, 8, 10", "2, 4", "15", "2", "true", "true"]),
        }
        if args.test in test_files:
            name, filepath, expected = test_files[args.test]
            with open(filepath, 'r') as f:
                source = f.read()
            debug_test(name, source, expected)
        else:
            print(f"Available tests: {', '.join(test_files.keys())}")
    else:
        # Demo debug
        demo_code = """let x = 5;
let y = 10;
console.log(x + y);
"""
        debug_full(demo_code, "Demo")

if __name__ == '__main__':
    main()
